// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Runtime check: if missing on load, venues and other Supabase data will fail (log once)
if (typeof window !== "undefined") {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error(
      "[Supabase] Missing config. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in env and redeploy."
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disable auto-detection so the SDK does NOT consume + clear the URL hash
    // before OAuthCallback can read the magic-link tokens. OAuthCallback handles
    // all token exchange explicitly.
    detectSessionInUrl: false,
  }
});